#include "proroach.h"

INICIAR PROGRAMA_MI
    INTEIRO A DE 10 ELEMENTOS RECEBE INICIO_CONJUNTO 10,2,4,2,5,9,1,0,6,4 FINAL_CONJUNTO;
    EXIBIR_VETOR DE_INTEIROS A COM 10 ELEMENTOS_NA_TELA;
FINALIZAR SEM_ERRO PROGRAMA_MF