#include "proroach.h"

COMECAR PROGRAMA
INICIO
    INTEIRO A DE 10 ELEMENTOS RECEBE INICIO_CONJUNTO 10,2,4,2,5,9,1,0,6,4 FIM_CONJUNTO FIM_DE_COMANDO
    EXIBIR_VETOR DE_INTEIROS A CONTENDO 10 ELEMENTOS_NA_TELA FIM_DE_COMANDO
    FINALIZAR SEM_ERRO
FIM